title: "Rotaract Library"
description: "Rotaract Library – an initiative by Rotaract South Asia MDIO to provide a curated library of project templates, checklists, and tools for Rotaract leaders."
baseurl: ""
url: "https://library.rsamdio.org"

markdown: kramdown
theme: null

plugins:
  - jekyll-sitemap
  - jekyll-feed

request_form_endpoint: "https://script.google.com/macros/s/AKfycbzNoSNmdYRuWAUNKfmcZK6Hb-C5SgD6NtYua3VFOe5bNF0qyONyeB4P5WuBSQSVDwSp/exec"

collections:
  resources:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: "resources"
    values:
      layout: resource_group
  - scope:
      path: "_resources/template.md"
    values:
      published: false

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

