[build]
  command = "npm ci && bundle install && bundle exec jekyll build"
  publish = "_site"

[[redirects]]
  from = "https://rsalibrary.netlify.app/*"
  to = "https://library.rsamdio.org/:splat"
  status = 301
  force = true

[[redirects]]
  # Fallback 404 page for any unmatched route
  from = "/*"
  to = "/404.html"
  status = 404